# Generated by Django 4.1.5 on 2023-04-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_end_date_listing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
