# Generated by Django 4.1.5 on 2023-04-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='duration',
        ),
    ]
