# Generated by Django 4.1.5 on 2023-04-27 15:48

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listing_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(null=True, validators=[auctions.models.Listing.date_validator]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_date',
            field=models.DateTimeField(null=True, validators=[auctions.models.Listing.date_validator]),
        ),
    ]
