# Generated by Django 4.1.5 on 2023-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_active_status_alter_listing_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active_status',
        ),
    ]
